//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventar.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventar.Resources.Resource - Copy", typeof(Resource___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Product.
        /// </summary>
        public static string AddNewProduct {
            get {
                return ResourceManager.GetString("AddNewProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Payment.
        /// </summary>
        public static string AddPayment {
            get {
                return ResourceManager.GetString("AddPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Paid.
        /// </summary>
        public static string AmountPaid {
            get {
                return ResourceManager.GetString("AmountPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string BackToList {
            get {
                return ResourceManager.GetString("BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyer Information.
        /// </summary>
        public static string BuyerInfo {
            get {
                return ResourceManager.GetString("BuyerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buyers.
        /// </summary>
        public static string Buyers {
            get {
                return ResourceManager.GetString("Buyers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buys.
        /// </summary>
        public static string Buys {
            get {
                return ResourceManager.GetString("Buys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Purchase.
        /// </summary>
        public static string ConfirmPurchase {
            get {
                return ResourceManager.GetString("ConfirmPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Product.
        /// </summary>
        public static string CreateProduct {
            get {
                return ResourceManager.GetString("CreateProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Full Name.
        /// </summary>
        public static string CustomerFullName {
            get {
                return ResourceManager.GetString("CustomerFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Buyer.
        /// </summary>
        public static string DeleteBuyer {
            get {
                return ResourceManager.GetString("DeleteBuyer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Payment.
        /// </summary>
        public static string DeletePayment {
            get {
                return ResourceManager.GetString("DeletePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Product.
        /// </summary>
        public static string DeleteProduct {
            get {
                return ResourceManager.GetString("DeleteProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Sale.
        /// </summary>
        public static string DeleteSale {
            get {
                return ResourceManager.GetString("DeleteSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string DeleteThis {
            get {
                return ResourceManager.GetString("DeleteThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Payment.
        /// </summary>
        public static string EditPayment {
            get {
                return ResourceManager.GetString("EditPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Product.
        /// </summary>
        public static string EditProduct {
            get {
                return ResourceManager.GetString("EditProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sale.
        /// </summary>
        public static string EditSale {
            get {
                return ResourceManager.GetString("EditSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Items.
        /// </summary>
        public static string InventoryItems {
            get {
                return ResourceManager.GetString("InventoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left To Pay.
        /// </summary>
        public static string LeftToPay {
            get {
                return ResourceManager.GetString("LeftToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m² per Product.
        /// </summary>
        public static string M2PerProduct {
            get {
                return ResourceManager.GetString("M2PerProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m² Total.
        /// </summary>
        public static string M2Total {
            get {
                return ResourceManager.GetString("M2Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually Enter Id.
        /// </summary>
        public static string ManuallyEnterId {
            get {
                return ResourceManager.GetString("ManuallyEnterId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found!.
        /// </summary>
        public static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per m².
        /// </summary>
        public static string PerM2 {
            get {
                return ResourceManager.GetString("PerM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Total.
        /// </summary>
        public static string PriceTotal {
            get {
                return ResourceManager.GetString("PriceTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print PDF.
        /// </summary>
        public static string PrintPDF {
            get {
                return ResourceManager.GetString("PrintPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID.
        /// </summary>
        public static string ProductID {
            get {
                return ResourceManager.GetString("ProductID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Number.
        /// </summary>
        public static string ProductNumber {
            get {
                return ResourceManager.GetString("ProductNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales By Day.
        /// </summary>
        public static string SalesByDay {
            get {
                return ResourceManager.GetString("SalesByDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Report.
        /// </summary>
        public static string SalesReport {
            get {
                return ResourceManager.GetString("SalesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Time.
        /// </summary>
        public static string SaleTime {
            get {
                return ResourceManager.GetString("SaleTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan QR Code.
        /// </summary>
        public static string ScanQRCode {
            get {
                return ResourceManager.GetString("ScanQRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        public static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Quantity.
        /// </summary>
        public static string TotalQuantity {
            get {
                return ResourceManager.GetString("TotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Spent.
        /// </summary>
        public static string TotalSpent {
            get {
                return ResourceManager.GetString("TotalSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Payment History.
        /// </summary>
        public static string ViewPaymentHistory {
            get {
                return ResourceManager.GetString("ViewPaymentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Payments.
        /// </summary>
        public static string ViewPayments {
            get {
                return ResourceManager.GetString("ViewPayments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Sales Report.
        /// </summary>
        public static string ViewSalesReport {
            get {
                return ResourceManager.GetString("ViewSalesReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
